import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LiteRead',
  description: 'Generated by LiteRead Setup',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body className={inter.className}>
        {/* Navbar 在阅读页可能需要隐藏，这里简单处理为全局显示，阅读页通过 CSS 覆盖 */}
        {children}
      </body>
    </html>
  );
}